### ISSUE TITLE
Can we use SimpleTimer with NodeMCU v1.0

### ISSUE THREAD

**Issue by Nikitha-Kondapalli** [schinken/SimpleTimer#5]
Is simpletimer compatible only with Arduino or nodemcu

Actually we are facing a problem while calling timer.setTimeout(t_ms, f) in nodemcu, where f is void function. The instructions in the function f are not executing.

**Comment by schinken** [comment]
I totally use it all day with my NodeMCUs. See here for examples:

https://github.com/b4ckspace/esp8266-laserabluftdruckmessung/blob/master/esp8266-laserabluftdruckmessung.ino#L131
