### ISSUE TITLE
SNAFU

### ISSUE THREAD

**Issue by ghost** [schinken/SimpleTimer#7]
C:\Program Files (x86)\Arduino\libraries\SimpleTimer/SimpleTimer.h:37:22: fatal error: functional: No such file or directory

 #include <functional>

error

**Comment by schinken** [comment]
It seems that the arduino IDE doesn't include <functional> for mega/uno/etc. Thinking about a wordaround for that. Because I want to stay with std::function.

You can use the original version which will not have this problem: https://github.com/schinken/SimpleTimer/blob/master/README.md
